website:
  title: "Leonardo Torres"
  image: media/Headshot.jpg
  navbar:
    left:
      - href: index.qmd
        text: Me!
      - href: about.qmd
        text: About Info
      - href: resources.qmd
        text: Resources!
      - href: projecttwo.qmd
        text: Netflix Project 2
      - href: project3.qmd
        text: Probability of High Start in BlackJack!
      - text: "Data Viz"
        menu:
          - text: "Visualizations of Rolling Stone Albumes and UFO Sightings!"
            href: DataVisualization.qmd


format:
  html:
    theme:
      light: lux
      dark: cyborg
    css: styles.css
    toc: true
    page-layout: full

editor: visual

project:
  type: website
  output-dir: docs
  
# ~ additional metadata excluded for brevity ~

