website:
  title: "Leonardo Torres"
  image: media/Headshot.jpg
  navbar:
    left:
      - href: index.qmd
        text: Info about me
      - href: about.qmd
        text: Resume
      - href: resources.qmd
        text: Coding Projects
      - text: "Data Science Projects"
        menu:
          - text: "Genres throughout the Years"
            href: DataVisualization.qmd
          - text: "Reported UFO Sightings from US States"
            href: DataViz2.qmd
          - href: projecttwo.qmd
            text: "An Analytic look at Netflix Descriptions"
          - href: project3.qmd
            text: "Caluclation for Win Probability at Blackjack using Simulations"
          - href: project4.qmd
            text: "WAI  Database Analysis + Freq. vs Mean Absorption"
          - href: presentation.qmd
            text: "A Detailed look at Running Simulations"  
            


format:
  html:
    theme:
      light: lux
      dark: cyborg
    css: styles.css
    toc: true
    page-layout: full

editor: visual

project:
  type: website
  output-dir: docs
  
# ~ additional metadata excluded for brevity ~

