website:
  title: "Leont500.github.io"
  image: media/Headshot.jpeg
  toc: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
about:
  template: solana
  image-shape: rectangle
  image-width: 15em
  links:
  -text: LinkedIn
    href: https://www.linkedin.com/in/leonardotorrespomona/
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

project:
  type: website
  output-dir: docs
  
# ~ additional metadata excluded for brevity ~

