website:
  title: "Leonardo Torres"
  image: media/Headshot.jpg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      

about: 
  template: solana
  image-shape: rectangle
  image-width: 15em
  links:
    - text: LinkedIn
      href: https://www.linkedin.com/in/leonardotorrespomona/

        
# page content excluded for brevity ~


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

project:
  type: website
  output-dir: docs
  
# ~ additional metadata excluded for brevity ~

